# Generated by Django 5.2.3 on 2025-06-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('price_band', models.CharField(max_length=100)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('listed', 'Listed')], max_length=20)),
                ('ipo_price', models.FloatField(blank=True, null=True)),
                ('listing_price', models.FloatField(blank=True, null=True)),
                ('current_market_price', models.FloatField(blank=True, null=True)),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
            ],
        ),
    ]
